import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.scss";
import { Header } from "@/widgets/Header";
import { Footer } from "@/widgets/Footer";

const SfPro = localFont({
  src: "../../public/fonts/SF-Pro.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Halyk Zeinet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={SfPro.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
