import type { Metadata } from "next";
import { NextUIProvider } from "@nextui-org/react";
import localFont from "next/font/local";
import { Header } from "@/widgets/Header";
import "./styles/globals.scss";

const SfPro = localFont({
  src: "../../public/fonts/SF-Pro.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Halyk Zeinet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={SfPro.className}>
        <NextUIProvider>
          <Header />
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
