import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";

const SfPro = localFont({
  src: "../../public/fonts/SFUIText-Regular.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Halyk Zeinet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={SfPro.className}>{children}</body>
    </html>
  );
}
